before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/keeper
    binary: keeper
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
dockers:
  - dockerfile: .goreleaser.dockerfile
    goos: linux
    goarch: amd64
    goamd64: v2
    image_templates:
      - "ghcr.io/bruno-chavez/keeper:{{ .Tag }}"
      - "ghcr.io/bruno-chavez/keeper:v{{ .Major }}"
      - "ghcr.io/bruno-chavez/keeper:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/bruno-chavez/keeper:latest"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
